navbar
macfer79/grupoProyectosFrontEnd pull request #1
Opened 2024-06-02 15:53 UTC by TizoG

Navbar con botón que podríamos enlazar al proyecto.

2024-06-08 15:37 UTC, macfer79 requested changes
Buenas TizoG, este navbar me gusta bastante, aunque tienes que tener en cuenta que la mayoria están aprendiendo y lo poco que hemos decidido por el momento en el grupo es ir despacio, así que si puede realizar los arreglos oportunos para que en la línea 7 la parte de javascript se eliminase, aprobaría la pull request sin problema. Un saludo.

2024-06-18 06:55 UTC, TizoG commented
Lo de la línea 7 es un script para incluir los iconos, en cuanto tenga un hueco libre lo modifico.

2024-06-20 15:32 UTC, macfer79 approved these changes

2024-06-20 15:33 UTC, macfer79 commented
Me parece bien

2024-06-20 15:33 UTC, macfer79 approved these changes

2024-06-20 15:37 UTC, merged